import { type NextPage } from "next";
import Head from "next/head";
import Profile from "./profile";

import SignUp from "./signup";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/* <SignUp /> */}
        <Profile/>
    </>
  );
};

export default Home;
